# Generated by Django 3.0.3 on 2020-07-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.CharField(max_length=200)),
                ('userId', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('review_help_total', models.PositiveIntegerField()),
                ('review_help_help', models.PositiveIntegerField()),
                ('review_score', models.FloatField()),
                ('review_time', models.DateTimeField()),
                ('review_summary', models.TextField()),
                ('review_text', models.TextField()),
            ],
        ),
    ]
