# Generated by Django 3.0.3 on 2020-07-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_search_app', '0003_fts_update_trigger'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.AlterField(
            model_name='ftsreview',
            name='productId',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='ftsreview',
            name='userId',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
